### ISSUE TITLE
Volume API data is not in phase with sensor data

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-CNS/RADAR-RestApi#116]
This is related to the dashboard volume graph and sensor graphs in subject page.
<img width="681" alt="screen shot 2018-07-16 at 15 00 30" src="https://user-images.githubusercontent.com/16977973/42762766-0e7b05b8-8909-11e8-9f64-b919dee3ec4d.png">

If for example, Volume API gets aggregate data between current time and one year ago (requests are seen below): 
Dates of data returned will be [2017-07-15, 2017-07-22, 2017-07-29, ..., **2017-05-26**, ..]

When these dates are used to get data from sensors, sensors return dates where it has data in between requested timeframe: 

Request:
`https://radar-cns-platform.rosalind.kcl.ac.uk/api/data/RADAR-MDD-KCL-s1/e9780f3a-e671-477c-90a7-e7b02d25e167/57903152-95fc-41d1-be61-ac156e2d0362/ANDROID_PHONE_v1_BATTERY/MEDIAN?timeWindow=ONE_WEEK&startTime=2017-07-15T23:00:00Z&endTime=2018-07-16T14:11:55.543Z`

Dates of data returned will be [2018-04-05, ..., 2018-05-24, **2018-05-31**, ...]

One example:
So in the sensors data, the data is seen on 2018-05-31, but in volume graph the data is seen on 2018-05-26.

As a result: 

Current implementation:

Volume API Request (from Current Date): `https://radar-cns-platform.rosalind.kcl.ac.uk/api/aggregate/RADAR-MDD-KCL-s1/e9780f3a-e671-477c-90a7-e7b02d25e167/distinct?startTime=2017-07-15T23:00:00.000Z&endTime=2018-07-16T14:11:55.543Z`

<img width="220" alt="screen shot 2018-07-16 at 14 11 05" src="https://user-images.githubusercontent.com/16977973/42762056-2d1ba3ee-8907-11e8-8415-a36c603f2585.png">
(The area chart peak is at 05-26)

This should be:

Volume API Request:
`https://radar-cns-platform.rosalind.kcl.ac.uk/api/aggregate/RADAR-MDD-KCL-s1/e9780f3a-e671-477c-90a7-e7b02d25e167/distinct?startTime=2017-07-12T23:00:00.000Z&endTime=2018-07-12T23:00:00.000Z`

<img width="262" alt="screen shot 2018-07-16 at 14 09 35" src="https://user-images.githubusercontent.com/16977973/42762032-1e8d95e4-8907-11e8-83a8-2bbfa6ad6c5b.png">
(The area chart peak should be at 05-31)

So they are not 'in-phase' in terms of dates.

I'm not sure what the solution should be, since seeing it now, the possible solution would be letting the volume api return the last date with data so the sensors dates are in sync with the volume api dates.

But this may be a problem when different sources would have different dates as well. As a result, these may be out of sync or out of phase as well.

**Comment by nivemaham** [comment]
Could you also mention the requests for both cases?

**Comment by blootsvoets** [comment]
The volume API, for `ONE_WEEK` data, the dates returned with a time point concern the entire week coming after that. So if on Tuesday something was collected, and on Thursday something else, everything will be mapped to the same week, with time point Monday (for example). If in the week after that no data was collected, the next Monday will contain no data.

For a graph, the data could perhaps be mapped as a bar chart rather than a line chart, since it concerns rough aggregated data. So then there would be a bar spanning from this Monday up to the next, containing the value of this Monday. Alternatively, you could shift the center of each time point half a week, so that at more closely resembles an "average" for a week. That would remain less accurate though. For a finer granularity, a `ONE_DAY` aggregate might be more appropriate, perhaps with a scrollbar or date selector to shift to earlier months/years.

**Comment by mpgxvii** [comment]
I think the `ONE_DAY` aggregate would be best. Because there's an issue with weeks. For example on the volume graph the week with data is May 26, while in the sensors graphs the week with data is May 31st. But if you zoom in more to get `ONE_HOUR` time windows around that time, the data is on June 5th, which is covered by the week of May 31 but not by the week of May 26.

**Comment by nivemaham** [comment]
Indeed. ONE_DAY graph would give output that is closer to the sensor data when zoomed in.

**Comment by afolarin** [comment]
@blootsvoets suggestion looks good. I think this is actually much closer to what we actually want as the histogram additionally shows a "shoulder" which is misleading, the stacked barchart is cleaner representation of the volume.
