### ISSUE TITLE
Data for subject endpoints should be fetched from ManagementPortal

### ISSUE THREAD

**Issue by dennyverbeeck** [RADAR-CNS/RADAR-RestApi#33]
The `getAllSubjects` and `getSubject` endpoints should get their data from ManagementPortal

**Comment by yatharthranjan** [comment]
The following have been implemented in this commit [9b8463445396c2b9723ae1a90c24360b27ce6c34 ](https://github.com/RADAR-CNS/RADAR-RestApi/commit/9b8463445396c2b9723ae1a90c24360b27ce6c34) on the branch [resolve_get_subjects_issue](https://github.com/RADAR-CNS/RADAR-RestApi/tree/resolve_get_subjects_issue)  according to guidelines in issue #42 

- [x] /api/mp/subjects
- [x] /api/mp/subjects/{id}
- [x] /api/mp/projects/{id}/subjects
- [x] /api/mp/projects/{id}

The following have been implemented but do not provided intended results because of this issue of MP [issue 18](https://github.com/RADAR-CNS/ManagementPortal/issues/18). Once this issue is resolved, this should work.
- [x] /api/mp/projects 

A separate endpoint (`/mp`) has been created for exposing data retrieved from the MP for now. This can later be merged into (`/api`)
Here {id} of subject in Rest-API = {login} of subject in MP
All of this data is retrieved from the MP and formatted and exposed through REST-API.

**Comment by yatharthranjan** [comment]
closed with #43
